### ISSUE TITLE
Selenium 4.x support

### ISSUE THREAD

**Issue by stevepryde** [stevepryde/thirtyfour#103]
I would like to add support for selenium 4.x.

This ticket is for scoping out what that looks like, what is required etc.
* Please add comments requesting any official selenium 4.x features to support in `thirtyfour`
* If you are reading this and have experience with Selenium 4.x and can help out, that would be greatly appreciated!

**Comment by stevepryde** [comment]
@rv-uhimely please open an issue on [fantoccini](https://github.com/jonhoo/fantoccini/issues) for this. Thirtyfour uses fantoccini for all communication with the webdriver/selenium.
Thanks.

**Comment by lamalex** [comment]
This has been fixed upstream. Linked PR bumps fantoccini version to include `charset=utf-8` on `Content-Type` when starting a webdriver session.
