### ISSUE TITLE
Can I specify the chrome path?

### ISSUE THREAD

**Issue by MaoQiankun97** [stevepryde/thirtyfour#105]
Can I specify the chrome path? like selenium of python version:
```
options = Options()
options.binary_location = "/path/to/chrome"
```

**Comment by stevepryde** [comment]
Yes, you should be able to do this:
```rust
let mut caps = DesiredCapabilities::chrome();
caps.set_binary("/path/to/chrome");
```

This is just a helper for:
```rust
self.add_chrome_option("binary", "/path/to/chrome");
```

Which is roughly equivalent to the python code here:
https://github.com/SeleniumHQ/selenium/blob/trunk/py/selenium/webdriver/chromium/options.py#L170

Let me know if this doesn't work.

**Comment by MaoQiankun97** [comment]
It works! Thank you!
