### ISSUE TITLE
Cannot connect chrome debug window

### ISSUE THREAD

**Issue by zemelLeong** [stevepryde/thirtyfour#123]
I want to connect chrome debug window avoid website anti bot detect got this error: `NewSessionError(NotW3C(String("")))`

steps:
- execute cmd start chrome debug window: `chrome --remote-debugging-port=9222 --user-data-dir="H:\chrome-data-path"`

- try to use `thirtyfour` connect:
```rust
    let caps = DesiredCapabilities::chrome();

    let driver = WebDriver::new(
        "http://localhost:9222", caps
    ).await.map_err(|_e| { 
        println!("{:?}", _e);
        "init got error".to_string()
    })?;
```

- then `println!` output error: `NewSessionError(NotW3C(String("")))`

the idea is from this article: https://abodeqa.com/how-to-connect-selenium-to-existing-chrome-browser/

how can I fix it? thanks.

**Comment by stevepryde** [comment]
You'll need to set the experimental option in the capabilities.
Try this:
```rust
let mut caps = DesiredCapabilities::chrome();
caps.set_debugger_address("http://localhost:9222")?;
let driver = WebDriver::new("http://localhost:9222", caps).await.map_err(|e| ..)?;
```

**Comment by zemelLeong** [comment]
Seems not work.
This code:
```rust
use anyhow::Ok;
use thirtyfour::prelude::*;

#[tokio::test]
async fn remote_debugging() -> anyhow::Result<()> {
  let mut caps = DesiredCapabilities::chrome();
  caps.set_debugger_address("http://localhost:9222")?;
  let driver = WebDriver::new("http://localhost:9222", caps).await?;
  driver.goto("https://www.baidu.com").await?;
  Ok(())
}
```

got this error:
```
Caused by:
    webdriver server gave non-conformant response: String("")
```

**Comment by stevepryde** [comment]
That might be a different error. You probably also need a `chromedriver` instance running as well. The java lib probably starts one implicitly (thirtyfour doesn't support this yet - it's on my todo list). I think you would need to start chromedriver then point the `WebDriver` at `http://localhost:9515` (default port for chromedriver is 9515). So the debugger address needs to be set to `localhost:9222` and you connect the `WebDriver` to `http://localhost:9515`. Give that a try.

**Comment by zemelLeong** [comment]
It works. Thank you so much.
```rust
use anyhow::Ok;
use thirtyfour::prelude::*;

#[tokio::test]
async fn remote_debugging() -> anyhow::Result<()> {
  let mut caps = DesiredCapabilities::chrome();
  caps.set_debugger_address("localhost:9222")?;
  let driver = WebDriver::new("http://localhost:9515", caps).await?;
  driver.goto("https://www.baidu.com").await?;
  Ok(())
}
```

**Comment by stevepryde** [comment]
Awesome. It would be good to have something like this as an example.
