### ISSUE TITLE
Unable to hide/disable "DevTools listening on..." while using ChromeDriver

### ISSUE THREAD

**Issue by bamcneely** [stevepryde/thirtyfour#130]
The JavaScript and Python (and maybe other?) Selenium implementations allow passing experimental options, specifically "exclude switches" to Chrome with the argument "enable-logging" to completely disable all logging including the "DevTools listening on..." message.

[JavaScript Example](https://bugs.chromium.org/p/chromedriver/issues/detail?id=3411)
[Python Example](https://bugs.chromium.org/p/chromedriver/issues/detail?id=2907)

This appears to be the only way to disable the messages, but this functionality is not available when using Rust/thirtyfour.

**Comment by stevepryde** [comment]
I've just published `0.32.0-rc.2` which adds `ChromeCapabilities::add_exclude_switch()` which should provide the functionality you need. Let me know if that works for you.

**Comment by bamcneely** [comment]
I just tested using `0.32.0-rc.3` and it appears to work perfectly. Thank you so much!
