### ISSUE TITLE
Query element does not wait or work

### ISSUE THREAD

**Issue by sunshine69** [stevepryde/thirtyfour#137]
Hi team,

I really like the repo - the way to work with is very logical and easy.

However I hit something strange.

Why this code 
```
    let mut count = 0;
    while count < 5 {
            println!("count: {}", count);
        if driver.query(By::Id(ele_id)).not_exists().await.unwrap() {
            println!("not existed yet, sleeping 3 sec now");
            thread::sleep(Duration::new(3, 0) );
            count = count + 1;
        } else {
            println!("existed!");
            break;
        }
    }
```

never works - it always says no such element 

But simple this works

```
 driver.query(By::Id(ele_id)).first().await?;
```

At first I tried 
```
driver.query(By::Id(ele_id)).exists().await?;
thread::sleep(Duration::new(3, 0));
```
instead of the while loop and it does not work as well.

Directly using `find` wont work of course as it needs some time to load the element.

Thanks

**Comment by stevepryde** [comment]
If you just want to wait for an element to appear, this is the recommended way:

```rust
driver.query(By::Id(ele_id)).first().await?;
```

This will implicitly poll until the element shows up, or it will timeout after 30 seconds (the default timeout, which can be changed).

Meanwhile I will have a look into the `exists()` and `not_exists()` methods. Bear in mind those methods will also poll until the condition is true. You could try with `.nowait()` in the method chain and see if that makes a difference.

**Comment by sunshine69** [comment]
Interest in finding if any bugs in `exists()` or `not_exists()` but I am too new to rust to do more.
I will try `nowait()` in the for loop and update here soon

**Comment by sunshine69** [comment]
OK did try into
```
while count < 5 {
            println!("count: {}", count);
        if driver.query(By::Id(ele_id)).nowait().not_exists().await? {
            println!("not existed yet, sleeping 3 sec now");
            thread::sleep(Duration::new(3, 0) );
            count = count + 1;
        } else {
            println!("existed!");
            break;
        }
    }
```

Run it - it always pass over and never reach the `else` part. That is count is full of iterations. However the next line (not display here) of `find` found the ele and run as normal.

So still something not quite right. If someone can have a look and see what potential bugs in there. For now I will use the `first`.

**Comment by sunshine69** [comment]
For the full script - https://github.com/sunshine69/selenium-rust-example-restart-router/blob/main/src/main.rs if it helps debugging

**Comment by stevepryde** [comment]
I found a bug that would affect the `exists()` and `not_exists()` code in the case where they time out. When `run_poller()` times out it returns `Vec::new()` which is not correct here.

I'm refactoring this a bit and also adding some more retrievers (match all selectors etc).
And of course adding a unit test to cover these cases.

**Comment by stevepryde** [comment]
This should be fixed in `v0.32.0-rc.4`. If you get a chance to try it out, I'd be keen to know if this solves your original issue.

However as discussed before, the `first()` or `single()` methods are really what you want when waiting for an element to show up, since these will poll until the element is there, and then return the element.

**Comment by sunshine69** [comment]
Hi mate,
Thanks to have a look.  I tested this `driver.query(By::Id(ele_id)).not_exists().await.unwrap() ` and it works now as expected.

Also the better one still works - that is `driver.query(By::Id(ele_id)).first().await?;`

Noticed that you deprecate the `.add_chrome_arg` in cap, but use `.add_arg()` ; is it intentional? as it will break old code if not.

cheers

**Comment by stevepryde** [comment]
> Noticed that you deprecate the `.add_chrome_arg` in cap, but use `.add_arg()` ; is it intentional? as it will break old code if not.

Yeah this is intentional. I did a major refactor of the capabilities methods to better align chrome and firefox (and others).

I just noticed the docs are wrong on that method though. I'll need to fix that.

**Comment by sunshine69** [comment]
All good, closing this ticket now
