### ISSUE TITLE
Any way to launch without downloading separate chrome driver?

### ISSUE THREAD

**Issue by rohitcoder** [stevepryde/thirtyfour#138]
HI,

I was trying this and I noticed I had to download a separate chromedriver from https://chromedriver.chromium.org/downloads and then I had to use.

```rust
let driver = WebDriver::new("http://localhost:9515", caps).await?;
```
Another challenge was, if my browser is outdated then I had to first update it and then download the latest chrome driver.

I want to make this process super simple, I already used this https://crates.io/crates/headless_chrome but it's super slow, so i wanted to test this lib.

I'm making a product for end user and setting up these multiple things won't be a good idea, end users aren't tech-savvy.  headless_chrome doesn't require any kind of configuration. So, is there anyway to detect the browser automatically and use it, or if lib downloads and setup everything on its own, something like that?

**Comment by stevepryde** [comment]
This crate uses the WebDriver protocol so yes you will need a webdriver running. I think puppeteer and others use the Chrome DevTools Protocol directly, which I'm guessing is more like the protocol used between chromedriver and chrome. However CDP is very chrome-specific in some cases and is not a strict standard like the WebDriver protocol. While major browsers support some of it, it's not clear whether it will ever be fully adopted.

However you may be interested in #127 , which would allow thirtyfour to download the correct version of chromedriver automatically and run it locally. I think that's still a way off though.

**Comment by stevepryde** [comment]
Have a look at Selenium Manager: https://github.com/SeleniumHQ/selenium/tree/trunk/rust
It should be possible to interact with it as a lib as well. See the thirtyfour README:
https://github.com/stevepryde/thirtyfour#using-selenium-manager

**Comment by stevepryde** [comment]
@rohitcoder not sure if you're still looking into this but if you're looking for a painless way to run selenium without worrying about browser versions and webdriver versions, I'd recommend using docker. There are official docker images put out by the selenium project: https://github.com/SeleniumHQ/docker-selenium

These are super convenient both for local development and in "production". You can use RDP to view the browsers in real time, and even keep developing alongside while they are running. An issue you often face with other options is that the browser will capture keyboard focus especially when capturing a screenshot, and if you're typing you may end up typing something into a text field and accidentally fail a test. The docker approach solves that. But once you set it up I think using docker to manage selenium is just much easier. It's painless to always update to the latest version of each browser.

**Comment by rohitcoder** [comment]
Steve, thanks for your reply. I am no longer working on that issue, but I recall the challenge. Docker wasn't suitable for me as I was developing a CLI tool and needed to use selenium/playwright for web scraping, as normal scraping was easily blocked by Cloudflare. But, I do acknowledge that using docker could have been a quicker solution.
