### ISSUE TITLE
usr/bin/ld: i386 architecture of input file is incompatible with i386:x86-64 output

### ISSUE THREAD

**Issue by savethebeesandseeds** [stevepryde/thirtyfour#139]
On running `cargo build` for a project with thirtyfour rust dependency. 
Some bindings where compiled in `cc -m32` and some where compiled in `cc -m64`. To solve this problem I've created a local file in the project root directory named build.rs

`fn main() {
    println!("cargo:rustc-link-arg=-m64");
}`

This solved the problem.

**Comment by stevepryde** [comment]
I'm not sure how this relates to thirtyfour itself. Can you elaborate?
