### ISSUE TITLE
Running tests with separate driver in bitbucket pipelines.

### ISSUE THREAD

**Issue by bcpeinhardt** [stevepryde/thirtyfour#154]
This issue is adjacent to thirtyfour because thirtyfour does not currently manager webdriver processes.

I am trying to run some tests based on thirtyfour against a standalone process (could be selenium or chromedriver I'm happy with either) in a bitbucket pipeline. 

I've run into about 50 errors trying various configurations to make this work. Could you point me to an example of running tests against a standalone webdriver process in CI/CD to give me an idea of how to get this working? Honestly anything helps.

**Comment by stevepryde** [comment]
The only thing I can suggest is to look at the CI for this repo.
