### ISSUE TITLE
When set_headless for chrome chrome=111.0.5563.146, cannot locate loginsubmit button

### ISSUE THREAD

**Issue by inevity** [stevepryde/thirtyfour#162]
head chrome is ok

**Comment by stevepryde** [comment]
Another thing to watch out for with headless browsers are any animations in CSS that may execute on page open or when you activate the browser tab. A headless browser will often behave like it's permanently minimized so any such animations will not run.

There are other subtleties that affect headless browsers too. Try googling for your issue and see if that helps. Note that this project is effectively for Rust bindings to selenium/webdriver and not for the webdriver implementation itself.
