### ISSUE TITLE
add_arg is not found within EdgeCapabilities

### ISSUE THREAD

**Issue by NightMare-Vortex** [stevepryde/thirtyfour#163]
In fact even arg wrappers like set_headless arent found within EdgeCapabilities

**Comment by stevepryde** [comment]
Hmm, yeah we probably need to abstract a lot of the chrome capabilities into a trait now and apply it to any chrome-based browsers. I'm not sure which capabilities might be unique to chrome vs shared with others though

**Comment by stevepryde** [comment]
Ah I just realised that pull request was yours. Thanks for that. I'm not yet sure if this would all be better with a trait. It probably would be. I suspect most/all chromium-based browsers will not modify the testing aspects of the browser much. They'll probably all stick very closely to chromium.

In any case I think the current interface is fine and should solve this issue. We can refactor later to reuse code a bit more.
