### ISSUE TITLE
A workaround for drag_and_drop_element

### ISSUE THREAD

**Issue by gz** [stevepryde/thirtyfour#165]
This is a workaround for `drag_and_drop_element(a, b)` that is working for me:

```rust
driver.action_chain()
    .move_to_element_center(&a)
    .perform()
    .await?;
tokio::time::sleep(Duration::from_millis(200)).await;
driver.action_chain()
    .click_and_hold_element(&a)
    .perform()
    .await?;
tokio::time::sleep(Duration::from_millis(200)).await;
driver.action_chain()
    .move_to_element_center(&b)
    .perform()
    .await?;
tokio::time::sleep(Duration::from_millis(200)).await;
driver.action_chain()
    .move_by_offset(-1,-1)
    .perform()
    .await?;
tokio::time::sleep(Duration::from_millis(200)).await;
driver.action_chain()
    .release()
    .perform()
    .await?;
tokio::time::sleep(Duration::from_millis(200)).await;
```

It's based on the findings from this comment: https://github.com/SeleniumHQ/selenium/issues/3269#issuecomment-452757044

Sorry that this isn't an issue but I figured I'd put it here so others don't also waste a day on this (FWIW I tried to use `js_drag_to` first but it didn't work for me). Maybe it can be put in the rustdocs of the method.

**Comment by stevepryde** [comment]
Thanks, I'll consider incorporating this

**Comment by stevepryde** [comment]
Is it possible to do all of this in a single action chain?

**Comment by stevepryde** [comment]
Hmm, note that the `js_drag_to()` method is unit tested.

I tried your given recipe both as-is and as a single action chain and both failed.

I'm going to close this issue. If you have a working recipe please consider submitting a PR with an accompanying test. Thanks.
