### ISSUE TITLE
so, how to get the text value of an element

### ISSUE THREAD

**Issue by Mon-ius** [stevepryde/thirtyfour#175]
I dive through the documents and the source code. 

But cannot find a quick-shot answer for the the text value of an element, e.g.

```html
`<strong>Code:&nbsp;27500003</strong>`
```

```Rust

let res = driver.find(By::Tag("strong")).await;
res.!todo()?????

```

I suggest to add such document at `README.md` to make things clear 🤗 

For solution:

```Rust
let res = driver.query(By::Tag("strong")).first().await?.text().await?;
let res = driver.find(By::Tag("strong")).await?.text().await?;
```

Note the `driver.query` vs `driver.find`

**Comment by bcpeinhardt** [comment]
The `WebElement` struct has two functions which may be of interest to you, `text` and `inner_html`.

https://docs.rs/thirtyfour/latest/thirtyfour/struct.WebElement.html#method.text
https://docs.rs/thirtyfour/latest/thirtyfour/struct.WebElement.html#method.inner_html

I think one of these will suit your purpose :)

The way you query the element is not related to what you can do with the element once you've found it.
