### ISSUE TITLE
Error while clicking element.

### ISSUE THREAD

**Issue by itehax** [stevepryde/thirtyfour#179]
`<area shape="default" role="button" aria-pressed="false" tabindex="0">`
This is the element i want to target,i'm able to get the element correctly,the problem is when i perform a click.
This is the error the webdriver gave to me(note: the element is clickable)

`Error: CmdError(Standard(WebDriver { error: JavascriptError, message: "javascript error: shape=default is not supported\n  (Session info: chrome=116.0.5845.188)", stacktrace: "" })) `

What can i do? Why does it gave me this error only when i try to click on this element?

**Comment by itehax** [comment]
@stevepryde

**Comment by bcpeinhardt** [comment]
Hey @itehax 
The error seems to indicate that selenium does not support clicking this element. So you have a few options
1. Try registering a click event "above" the element, something like:
```
driver
            .action_chain()
            .move_to_element_center(located_element)
            .click()
            .perform()
            .await
```
2. Figure out what the onclick function is, and execute that function manually using [the execute_async method on webdriver](https://docs.rs/thirtyfour/latest/thirtyfour/struct.WebDriver.html#method.execute_async). You could also simulate the click by executing a script that located the element and performed a click.

Hope one of these works for you :)

**Comment by itehax** [comment]
I tried the first approach and for some reason the function that allows me to move the mouse does not work for me in general,(not only move_to_element_center but also the others similar functions)

The second one I had thought about it and that is exactly what I will try.

ps,the item I am trying to click is the cloudflare button to verify that you are a human

**Comment by bcpeinhardt** [comment]
There's your problem!

Cloudflare doesn't want you to automate this (hence confirming personhood).

So you know, don't 🙂
