### ISSUE TITLE
Combobox interaction?

### ISSUE THREAD

**Issue by HagaiHargil** [stevepryde/thirtyfour#18]
Hi and thanks for this wonderful library. 

Could you please comment on whether or not it's possible to interact with a dropdown combobox? And if so, how?

Thanks.

**Comment by stevepryde** [comment]
What do you mean by "dropdown combobox" ? Depending on the framework used by the website you are interacting with, the process may be slightly different.

In general you should just be able to:
- Find the parent container element
- Click this parent element (this will open the dropdown)
- Find the option within the dropdown
- Click the option within the dropdown (this would usually select the item and close the dropdown)

**Comment by HagaiHargil** [comment]
Thanks for the quick response, I implemented you suggestion and it worked.
