### ISSUE TITLE
Connection refused when using containers

### ISSUE THREAD

**Issue by ctron** [stevepryde/thirtyfour#181]
I have some tests, which uses the following code to initialize the driver:

```rust
let caps =  DesiredCapabilities::chrome();
let driver = WebDriver::new("http://localhost:4444", caps).await?;
```

This works fine when I start `chromedriver --port=4444`  on my machine.

However, switching to the docker container, it fails with:

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: an unknown error occurred in the remote end whilst processing the command: unknown error: net::ERR_CONNECTION_REFUSED
  (Session info: chrome=117.0.5938.92)', integration-tests/src/ui.rs:111:43
```

However, a connection to `http://localhost:4444` is working.

**Comment by ctron** [comment]
Sniffing the TCP connection on port 4444, the last message I see there is:

```
HTTP/1.1 500 Internal Server Error
content-length: 1044
content-type: application/json; charset=utf-8
cache-control: no-cache

{"value":{"error":"unknown error","message":"unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=117.0.5938.92)","stacktrace":"#0 0x5607dbf1f6b3 \u003Cunknown>\n#1 0x5607dbbf51e7 \u003Cunknown>\n#2 0x5607dbbed2f3 \u003Cunknown>\n#3 0x5607dbbddd17 \u003Cunknown>\n#4 0x5607dbbdf191 \u003Cunknown>\n#5 0x5607dbbde053 \u003Cunknown>\n#6 0x5607dbbdd06c \u003Cunknown>\n#7 0x5607dbbdcfde \u003Cunknown>\n#8 0x5607dbbdbbe4 \u003Cunknown>\n#9 0x5607dbbdc06a \u003Cunknown>\n#10 0x5607dbbf78ce \u003Cunknown>\n#11 0x5607dbc77ad5 \u003Cunknown>\n#12 0x5607dbc5e0c2 \u003Cunknown>\n#13 0x5607dbc77322 \u003Cunknown>\n#14 0x5607dbc5de93 \u003Cunknown>\n#15 0x5607dbc30934 \u003Cunknown>\n#16 0x5607dbc3171e \u003Cunknown>\n#17 0x5607dbee4cb8 \u003Cunknown>\n#18 0x5607dbee8bf0 \u003Cunknown>\n#19 0x5607dbef319c \u003Cunknown>\n#20 0x5607dbee9808 \u003Cunknown>\n#21 0x5607dbeb627f \u003Cunknown>\n#22 0x5607dbf0de88 \u003Cunknown>\n#23 0x5607dbf0e059 \u003Cunknown>\n#24 0x5607dbf1e843 \u003Cunknown>\n#25 0x7fd10832b609 start_thread\n"}}
```

**Comment by stevepryde** [comment]
Is the webdriver server also running in docker? Have you tried with host networking enabled?

This looks like a docker issue, not a selenium/webdriver issue.

Could you try another selenium client in docker (python or java, for example) with the equivalent code and see if that makes any difference?

**Comment by ctron** [comment]
> Is the webdriver server also running in docker? Have you tried with host networking enabled?

It's the image from the readme. No, didn't try host networking.

> 
> This looks like a docker issue, not a selenium/webdriver issue.

I agree, it looks like some issue inside the container. I created an issue on their repo: https://github.com/SeleniumHQ/docker-selenium/issues/1958

**Comment by ctron** [comment]
I just tried with host networking and that seems to work. I am closing this issue, I don't think there is anything this crate can do about it.
