### ISSUE TITLE
How to use selenium-manager in my code?

### ISSUE THREAD

**Issue by carlosaherrera** [stevepryde/thirtyfour#182]
The [readme](https://github.com/stevepryde/thirtyfour#readme) makes reference to selenium-manager (https://github.com/stevepryde/thirtyfour#using-selenium-manager). After reading the [documentation](https://www.selenium.dev/documentation/selenium_manager/) of Selenium Manager, this looks to accomplish exactly what I want — which is automatic download and execution of drivers so that I am not constantly managing them manually.

I set 
```
selenium-manager = { git = "https://github.com/SeleniumHQ/selenium", branch = "trunk" }
```
in my `[dependencies]` as described. But how do I actually use it in my code? If we were to use your example code located at https://github.com/stevepryde/thirtyfour#example-async
```rs
use thirtyfour::prelude::*;

#[tokio::main]
async fn main() -> WebDriverResult<()> {
     let caps = DesiredCapabilities::chrome();
     let driver = WebDriver::new("http://localhost:9515", caps).await?;

     // Navigate to https://wikipedia.org.
     driver.goto("https://wikipedia.org").await?;
     let elem_form = driver.find(By::Id("search-form")).await?;

     // Find element from element.
     let elem_text = elem_form.find(By::Id("searchInput")).await?;

     // Type in the search terms.
     elem_text.send_keys("selenium").await?;

     // Click the search button.
     let elem_button = elem_form.find(By::Css("button[type='submit']")).await?;
     elem_button.click().await?;

     // Look for header to implicitly wait for the page to load.
     driver.find(By::ClassName("firstHeading")).await?;
     assert_eq!(driver.title().await?, "Selenium - Wikipedia");
    
     // Always explicitly close the browser.
     driver.quit().await?;

     Ok(())
}
```
what would I need to modify in order to get selenium-manager running?

**Comment by stevepryde** [comment]
If you run `cargo doc --open` do you get the docs for selenium-manager ?

**Comment by stevepryde** [comment]
Please refer to Selenium Manager docs for this. The use of Selenium Manager is currently outside the scope of this project.
