### ISSUE TITLE
How can I set the user-agent for Chromedriver?

### ISSUE THREAD

**Issue by new2rust** [stevepryde/thirtyfour#184]
Hi,

I know for Firefox I there is a method `set_user_agent()`: https://docs.rs/thirtyfour/latest/src/thirtyfour/common/capabilities/firefox.rs.html#239-241

or for python one can do something like:

```
from selenium.webdriver.chrome.options import Options
options = Options()
user_agent = "abc"
options.add_argument(f'--user-agent={user_agent}')
```

But how can it be done with Rust and the Chromedriver option?

Thanks in advance!

**Comment by c0d3sling3r** [comment]
If you're trying to set a mobile user-agent, there's another way I used and it worked!

```rust
let mut mobile_emulation_hashmap = HashMap::new();
mobile_emulation_hashmap.insert("deviceName", "<DEVICE_NAME>");
caps.add_chrome_option("mobileEmulation", mobile_emulation_hashmap)?;
```

And you can get device names from chrome device toolbar. Like: "Pixel 7"
![image](https://github.com/stevepryde/thirtyfour/assets/20586723/69a1c2c6-9599-4d69-b455-92ef4e61dcb7)
