### ISSUE TITLE
Chrome Options example erroring

### ISSUE THREAD

**Issue by rebekah** [stevepryde/thirtyfour#188]
**When I set up the example for Chrome Options:** https://github.com/stevepryde/thirtyfour/blob/86bd74c02bb850213f3199378d17bc9b2bf5afe8/thirtyfour/examples/chrome_options.rs

**I get this error:** error[E0599]: no method named `insert_browser_option` found for struct `ChromeCapabilities` in the current scope

Thanks in advance :)

**Comment by rebekah** [comment]
I had the wrong version - I was using 0.31.0 and I needed to be pulling directly from github branch main.

**Comment by stevepryde** [comment]
You may be able to point at the latest RC version which is `0.32.0-rc.8`
