### ISSUE TITLE
async webriver drop causes endless blocking

### ISSUE THREAD

**Issue by zhiburt** [stevepryde/thirtyfour#19]
### Issue

In `GenericWebDriver::drop` implementation `futures::executor::block_on` never returns if it run inside `tokio` runtime.
Specifically if driver is dropped inside a `tokio::task`.

Not sure if it's caused only by a usage of a different executor.

### To reproduce
```rust
        use thirtyfour::prelude::*;

        let driver = WebDriver::new("http://localhost:4444", &DesiredCapabilities::firefox()).await?;

        tokio::spawn(async move {
            println!("START");
            driver.close().await.unwrap();
            println!("FINISH");
        }).await;
```

You will see `START` and `FINISH` in output but it will never end the spawned task

> I spend a good number of hours to locate the issue :smiley:

**Comment by stevepryde** [comment]
This looks similar to #7. Async drop is not yet supported in Rust AFAIK which makes this difficult to do nicely. If you have an idea of how to improve it, please do.

For some context, see issue #7 and also this blog post: https://boats.gitlab.io/blog/post/poll-drop/

**Comment by stevepryde** [comment]
Calling `driver.quit().await` manually (instead of `driver.close().await`) might be an acceptable workaround for now.

**Comment by zhiburt** [comment]
I think it may by the best option.

**Comment by zhiburt** [comment]
Ohh, you've already implemented `quit` :+1: 

From the first look it does resolve the issue.

I will close this issue to to duplicate #7
