### ISSUE TITLE
How to set PageLoadStrategy::None in DesiredCapabilities::chrome()?

### ISSUE THREAD

**Issue by phw42** [stevepryde/thirtyfour#199]
### Discussed in https://github.com/stevepryde/thirtyfour/discussions/194

<div type='discussions-op-text'>

<sup>Originally posted by **KirDontsov** February 17, 2024</sup>
All of this works:
let _ = caps.add_chrome_arg("enable-automation");
let _ = caps.add_chrome_arg("--no-sandbox");
let _ = caps.add_chrome_arg("--disable-extensions");
let _ = caps.add_chrome_arg("--dns-prefetch-disable");
let _ = caps.add_chrome_arg("--disable-gpu");

All of this not works
let _ = caps.add_chrome_option("pageLoadStrategy", "NONE");
unexpected webdriver error; webdriver returned error: invalid argument: cannot parse capability: goog:chromeOptions
from invalid argument: unrecognized chrome option: pageLoadStrategy

let _ = caps.set_version("103");
unexpected webdriver error; webdriver returned error: invalid argument: unrecognized capability: version</div>

**Comment by stevepryde** [comment]
Resolved in v0.32.0. See the answer to the discussion (pasted below):

--

There's a dedicated method for this:
```rust
caps.set_page_load_strategy(PageLoadStrategy::None)?;
```
[Docs here](https://docs.rs/thirtyfour/latest/thirtyfour/common/capabilities/desiredcapabilities/trait.CapabilitiesHelper.html#method.set_page_load_strategy)
