### ISSUE TITLE
README example not working, getting `Error: SessionNotCreated, Unable to create new service: ChromeDriverService`

### ISSUE THREAD

**Issue by d1618033** [stevepryde/thirtyfour#2]
Steps to reproduce:

(1) Run `docker run --rm -d --network host --name selenium-server -v /dev/shm:/dev/shm selenium/standalone-chrome` 

(2) Run the example (async or sync)

Output:

`Error: SessionNotCreated(WebDriverErrorInfo { status: 500, error: "", value: WebDriverErrorValue { message: "Unable to create new service: ChromeDriverService\nBuild info: version: \'3.141.59\', revision: \'e82be7d358\', time: \'2018-11-14T08:25:53\'\nSystem info: host: \'dsternlicht\', ip: \'172.16.10.252\', os.name: \'Linux\', os.arch: \'amd64\', os.version: \'5.4.15-arch1-1\', java.version: \'1.8.0_232\'\nDriver info: driver.version: unknown", error: Some("session not created"), stacktrace: Some("org.openqa.selenium.SessionNotCreatedException: Unable to create new service: ChromeDriverService\nBuild info: version: \'3.141.59\', revision: \'e82be7d358\', time: \'2018-11-14T08:25:53\'\nSystem info: host: \'dsternlicht\', ip: \'172.16.10.252\', os.name: \'Linux\', os.arch: \'amd64\', os.version: \'5.4.15-arch1-1\', java.version: \'1.8.0_232\'\nDriver info: driver.version: unknown\n\tat org.openqa.selenium.grid.session.remote.ServicedSession$Factory.lambda$get$0(ServicedSession.java:135)\n\tat org.openqa.selenium.grid.session.remote.ServicedSession$Factory.apply(ServicedSession.java:152)\n\tat org.openqa.selenium.remote.server.ActiveSessionFactory.lambda$apply$12(ActiveSessionFactory.java:180)\n\tat java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)\n\tat java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:440)\n\tat java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)\n\tat java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)\n\tat java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)\n\tat java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)\n\tat java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)\n\tat java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)\n\tat java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)\n\tat java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)\n\tat java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:531)\n\tat org.openqa.selenium.remote.server.ActiveSessionFactory.apply(ActiveSessionFactory.java:183)\n\tat org.openqa.selenium.remote.server.NewSessionPipeline.lambda$null$2(NewSessionPipeline.java:66)\n\tat java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)\n\tat java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)\n\tat java.util.Collections$2.tryAdvance(Collections.java:4719)\n\tat java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)\n\tat java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)\n\tat java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)\n\tat java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)\n\tat java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)\n\tat java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)\n\tat java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:531)\n\tat org.openqa.selenium.remote.server.NewSessionPipeline.lambda$createNewSession$3(NewSessionPipeline.java:69)\n\tat java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)\n\tat java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)\n\tat java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)\n\tat java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:175)\n\tat java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)\n\tat java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)\n\tat java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)\n\tat java.util.stream.Streams$StreamBuilderImpl.tryAdvance(Streams.java:405)\n\tat java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:728)\n\tat java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)\n\tat java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)\n\tat java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)\n\tat java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)\n\tat java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)\n\tat java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)\n\tat java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:531)\n\tat org.openqa.selenium.remote.server.NewSessionPipeline.createNewSession(NewSessionPipeline.java:72)\n\tat org.openqa.selenium.remote.server.commandhandler.BeginSession.execute(BeginSession.java:65)\n\tat org.openqa.selenium.remote.server.WebDriverServlet.lambda$handle$0(WebDriverServlet.java:235)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: java.lang.reflect.InvocationTargetException\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat org.openqa.selenium.grid.session.remote.ServicedSession$Factory.lambda$get$0(ServicedSession.java:131)\n\t... 50 more\nCaused by: java.lang.RuntimeException: Unable to find a free port\n\tat org.openqa.selenium.net.PortProber.findFreePort(PortProber.java:67)\n\tat org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:351)\n\tat org.openqa.selenium.chrome.ChromeDriverService.createDefaultService(ChromeDriverService.java:94)\n\t... 55 more\n"), data: None } })
`

**Comment by tjtelan** [comment]
I was also unable to run the examples with the docker selenium startup in the README, but I did get it working with this version that isn't using the host network.
`docker run --rm -d -p 4444:4444 --name selenium-server -v /dev/shm:/dev/shm selenium/standalone-chrome:3.141.59-zinc`

FWIW, I was also able to reproduce the output from @d1618033 using a the firefox version of the container. I started the firefox container version like this:
`docker run --rm -d -p 4444:4444 --name selenium-server -v /dev/shm:/dev/shm selenium/standalone-firefox:3.141.59-zinc`

OS: MacOS 10.14
Docker: 19.03
Cargo: 1.40

**Comment by stevepryde** [comment]
I forgot that OSX does not work with host networking. I suspect that is the issue. I chose to use host networking for the example to avoid issues with DNS lookups in docker (which requires some config on OSX and possibly Ubuntu / other distros depending on how DNS is configured on the host).

This would probably work for you by using `-p 4444:4444` instead of `--network host`. If it complains of not being able to reach wikipedia (or whatever url you put in), you may need to also specify `--dns <your_dns_server_ip>` so that the container can resolve external DNS lookups.

There is a way to make the DNS setting permanent in the docker config. If you're on OSX, Docker desktop has a GUI for editing the config. On Linux, it's at `/etc/docker/daemon.json`.

Thanks @tjtelan, I'll check it out

**Comment by stevepryde** [comment]
@d1618033 I've merged in changes from @tjtelan that should fix your issue.

Let me know if this works for you now.

**Comment by d1618033** [comment]
Works great, thank you!
