### ISSUE TITLE
feature: innerHtml && outerHtml 

### ISSUE THREAD

**Issue by zhiburt** [stevepryde/thirtyfour#20]

**Comment by stevepryde** [comment]
Are you suggesting these be exposed as methods on WebElement?

The W3C WebDriver spec doesn't provide these directly but you can get them via javascript.

You would do something like this:
```rust
pub async fn inner_html(&self) -> WebDriverResult<String> {
    let mut args = ScriptArgs::new();
    args.push(&self)?;
    let ret = self.driver.execute_script_with_args(r#"return arguments[0].innerHtml;"#, &args).await?;
    ret.convert()
}
```

Please confirm if this is what you're after. This should be pretty easy to do.

**Comment by zhiburt** [comment]
This is one more solution how to obtain it

```
pub async fn inner_html(&self) -> WebDriverResult<String>
      self.get_property("innerHTML").await
}

pub async fn inner_html(&self) -> WebDriverResult<String>
     get_property("outerHTML").await
}

```

I think that it is unclear generally how to obtain such fields even though they are seemingly popular for checking/processing. Personally I haven't know a month ago that we can get these from property. Therefore I consider it might be reasonable to have methods even though it's one liners.

What do you think?

**Comment by stevepryde** [comment]
Aha I did not realise you could get those properties that way but it makes sense now. I've added those and I agree that these methods are very convenient and could save people some time.
