### ISSUE TITLE
DesiredCapabilities::default panic

### ISSUE THREAD

**Issue by zhiburt** [stevepryde/thirtyfour#21]
From my perspective `DesiredCapabilities::default()` isn't able to be any useful. It might be a good candidate for being deleted?  

```
'tests::test_ignore_url' panicked at 'called `Option::unwrap()` on a `None` value', /home/zhiburt/.cargo/registry/src/github.com-1ecc6299db9ec823/thirtyfour-0.15.1/src/common/capabilities/desiredcapabilities.rs:34:19
```

**Comment by stevepryde** [comment]
I've fixed the panic and also removed the Default derive for DesiredCapabilities. Since this technically breaks compatibility I'll bump the version to 0.16.0
