### ISSUE TITLE
How to pattern match an error type in 0.35.0

### ISSUE THREAD

**Issue by 9teta** [stevepryde/thirtyfour#257]
How to pattern match an error type in version 0.35.0
In 0.34.0 it was simple because they were enum types:
```

let r: Result<(), WebDriverError> = do_some_work(web_driver);
match r {
    Ok(_) => {},
    Err(WebDriverError::Timeout(_nf)) => {},
    Err(WebDriverError::NotFound(_item, _nf)) => {}
    Err(err) => {},
}

```

**Comment by flippette** [comment]
There's an `impl Deref<Target = WebDriverErrorInner> for WebDriverError` you can use like this:

```rust
let r: Result<(), WebDriverError> = /* ... */;
match r.map_err(|err| *err) {
    Ok(_) => {},
    Err(WebDriverErrorInner::Timeout(_)) => {},
    Err(WebDriverErrorInner::NotFound(_, _)) => {},
    Err(_) => {},
}
```

**Comment by 9teta** [comment]
> There's an `impl Deref<Target = WebDriverErrorInner> for WebDriverError` you can use like this:
> 
> ```rust
> let r: Result<(), WebDriverError> = /* ... */;
> match r.map_err(|err| *err) {
>     Ok(_) => {},
>     Err(WebDriverErrorInner::Timeout(_)) => {},
>     Err(WebDriverErrorInner::NotFound(_, _)) => {},
>     Err(_) => {},
> }
> ```

cannot move out of dereference of `WebDriverError`
move occurs because value has type `WebDriverErrorInner`, which does not implement the `Copy` trait

**Comment by 9teta** [comment]
> There's an `impl Deref<Target = WebDriverErrorInner> for WebDriverError` you can use like this:
> 
> ```rust
> let r: Result<(), WebDriverError> = /* ... */;
> match r.map_err(|err| *err) {
>     Ok(_) => {},
>     Err(WebDriverErrorInner::Timeout(_)) => {},
>     Err(WebDriverErrorInner::NotFound(_, _)) => {},
>     Err(_) => {},
> }
> ```
Actually my Results consists not only () in some cases and I get:

> cannot move out of dereference of `WebDriverError`
> move occurs because value has type `WebDriverErrorInner`, which does not implement the `Copy` trait

I mean
```rust
let r: Result<Vec<String>>, WebDriverError> = /* ... */;
match r.map_err(|err| *err) {
    Ok(ok) => { /* ... */ },
    Err(WebDriverErrorInner::Timeout(_)) => {},
    Err(WebDriverErrorInner::NotFound(_, _)) => {},
    Err(_) => {},
} 
```

**Comment by flippette** [comment]
There's also an `impl From<WebDriverError> for WebDriverErrorInner` so you can match on `r.map_err(WebDriverErrorInner::from)` too

**Comment by 9teta** [comment]
> There's also an `impl From<WebDriverError> for WebDriverErrorInner` so you can match on `r.map_err(WebDriverErrorInner::from)` too

Thank you. That works better. My refactoring became from: 
```rust
let r: Result<(), WebDriverError> = do_some_work(web_driver);
match r {
    Ok(_) => {},
    Err(WebDriverError::Timeout(_nf)) => {},
    Err(WebDriverError::NotFound(_item, _nf)) => {}
    Err(err) => {},
}
```
To
```rust
let r: Result<(), WebDriverErrorInner> = do_some_work(web_driver).await.map_err(WebDriverErrorInner::from);;
match r {
    Ok(_) => {},
    Err(WebDriverErrorInner::Timeout(_nf)) => {},
    Err(WebDriverErrorInner::NotFound(_item, _nf)) => {}
    Err(err) => {},
}
```
