### ISSUE TITLE
Impl driver.execute_cdp_cmd API

### ISSUE THREAD

**Issue by guoyucode** [stevepryde/thirtyfour#28]
This is the api of selenium, hope this library can achieve this function: execute_cdp_cmd 
This function is very useful and can be used to limit the operation of the webdriver, For example, the following example is: 
driver.execute_cdp_cmd("Page.addScriptToEvaluateOnNewDocument", {
        "source": """
            Object.defineProperty(navigator, 'webdriver', {
              get: () => undefined
            })
          """
    })

Thanks !

**Comment by stevepryde** [comment]
Weird, I had not heard of this command until now. I don't think it is part of the WebDriver spec at all but it seems to use the same W3C protocol to execute the commands.

It shouldn't be too difficult to implement this, going by the python code for it.

**Comment by stevepryde** [comment]
Turns out this will require a refactor of some core layers to remove lifetimes and allow for commands outside the core W3C spec to be passed through. I've started this work on the `command-refactor` branch (heads up in case anyone is following this issue).

I'm thinking this might need to be its own function or struct, rather than a method on `WebDriver` since it only applies to Chromium-based browsers. It would likely borrow the session and execute the command that way.

**Comment by stevepryde** [comment]
@guoyucode I've added initial support for the Chrome Devtools Protocol (CDP) on the `cdp` branch.

You can use it as follows:
```rust
let caps = DesiredCapabilities::chrome();
let driver = WebDriver::new("http://localhost:4444", &caps).await?;

// Use Chrome Devtools Protocol (CDP).
let dev_tools = ChromeDevTools::new(driver.session());
let mut conditions = NetworkConditions::new();
conditions.download_throughput = 20;
conditions.upload_throughput = 10;
dev_tools.set_network_conditions(&conditions).await?;
let conditions = dev_tools.get_network_conditions().await?;
assert_eq!(conditions.download_throughput, 20);
assert_eq!(conditions.upload_throughput, 10);
println!("Conditions: {:?}", conditions);

// Execute CDP command.
let version_info = dev_tools.execute_cdp("Browser.getVersion").await?;
println!("Chrome Version: {:?}", version_info["product"].as_str());
```
You can also specify parameters with `dev_tools.execute_cdp_with_params()` where the second parameter is a `serde_json::Value` containing any arguments you want to supply. This allows sending arbitrary args with any command.

Let me know what you think. I have not tested all of the functionality and probably won't be able to.

**Comment by stevepryde** [comment]
This has now been added in `v0.20.0`. Please open a new issue if you need anything further.
