### ISSUE TITLE
Connection refused (os error 111) with Firefox

### ISSUE THREAD

**Issue by Tritury** [stevepryde/thirtyfour#35]
Hello,

this error: `error sending request for url (http://localhost:6565/session): error trying to connect: tcp connect error: Connection refused (os error 111)` is returned by the WebClient new function when I call it.

How to reproduce:
1. run geckodriver using `./path/to/geckodriver --port=6565`
2. execute an application with the following code: `WebDriver::new("http://localhost:6565/", my_capabilities).await?;`

Implicitly waiting before calling ::new() doesn't work either.

**Comment by stevepryde** [comment]
I cannot reproduce the issue, sorry. The following code works fine for me:
```rust
let caps = DesiredCapabilities::firefox();
let driver = WebDriver::new("http://localhost:6565/", &caps).await?;
```

The error you listed suggests the geckodriver server is either not listening on the port you specified or is not running (i.e. that is the error message you would get if there was no server running/listening at that address)

As a separate test, try doing a POST request to http://localhost:6565/session with an empty JSON body and see if that works.
For example, the following curl command should start a new session:
```
curl --location --request POST 'http://localhost:6565/session' \
--header 'Content-Type: application/json' \
--data-raw '{}'
```
Let me know if that works or if you get the same error

**Comment by stevepryde** [comment]
Closed due to inactivity
