### ISSUE TITLE
More cookie getters

### ISSUE THREAD

**Issue by vtu-dog** [stevepryde/thirtyfour#37]
Hello!

I'm creating a web scraper. I have a website that's hard to log into using plain POST, so I create a temporary Selenium instance, log in and copy the session cookies to be later reused by `reqwest::Client`.

However, I ran into a problem - I have to access the `name` field of the `Cookie` struct, but it's private. I temporarily resorted to creating a `MyCookie` struct and invoking `unsafe { std::mem::transmute<Cookie, MyCookie>(instance) }`. Unfortunately this is risky, since `Cookie` is not a `#[repr(C)]` struct.

Please consider adding more getters to the struct, that would be immensely helpful.

**Comment by stevepryde** [comment]
Agreed. This looks like a bit of an oversight on my part.

**Comment by stevepryde** [comment]
Fixed in `v0.22.3`

**Comment by wandering-bison** [comment]
@vtu-dog is your code on github?

**Comment by vtu-dog** [comment]
@wandering-bison Sorry, it's private.

**Comment by wandering-bison** [comment]
> @wandering-bison Sorry, it's private.

kk, nw.
