### ISSUE TITLE
Reqwest feature "rustls-tls"

### ISSUE THREAD

**Issue by ianpurton** [stevepryde/thirtyfour#43]
First, thanks for a great project.

So I have an Actix Web project  project that uses rust-tls https://github.com/contor-systems/contor

I'm trying to write the integration tests with thirtyfour. https://github.com/contor-systems/contor/tree/master/tests

We're both using Reqwest accept I use the feature "rust-tls". I add thirtyfour as a dev-dependency.

Cargo doesn't have a way to disable dev dependencies during a build in my CI/CD. So I get an openssl error.

My first reaction was to look for a rust-tls feature on thirtyfour.

I can try some work arounds, but just thought I'd let you know.

**Comment by stevepryde** [comment]
I think the feature flag you are looking for is `reqwest-rustls-tls`. You can check the Cargo.toml file for available feature flags. Sorry these are not documented.
