### ISSUE TITLE
Check if element exists

### ISSUE THREAD

**Issue by Tockra** [stevepryde/thirtyfour#45]
Hi,

is there a way to check if a element on a page exists. Currently I'm using:

```rust
async fn html_contains_any_element_webdriver(driver: &WebDriver, url: &str, elements: Vec<&str>) -> Result<bool> {
    driver.get(url).await?;

    for element in elements.into_iter() {
        let filtered_elements = driver.find_element(By::XPath(element)).await;

        if filtered_elements.is_ok() {
            return Ok(true);
        }
    }

    Ok(false)
}
```
But this just returns after 30 seconds. 
Why does the crate needs 30 seconds to check if the current html contains an given element? (30 seconds for each element)

T

**Comment by Tockra** [comment]
Okay I found https://docs.rs/thirtyfour/0.23.0/thirtyfour/trait.WebDriverCommands.html#method.set_implicit_wait_timeout I will test this method.

**Comment by stevepryde** [comment]
Yes you are correct. It sets an implicit wait of 30 seconds by default just to get simple things running more reliably. However for more elaborate use cases you probably want implicit waits set to 0 and then do your own polling.

Also check out the `thirtyfour_query` crate for more element selector methods.

**Comment by bcpeinhardt** [comment]
@Tockra to follow up on what @stevepryde said, explicit or implicit waiting for an element that may or may not be there will slow down your program over time. I think a good idea might be to look for an element you know will be there nearby, for example the container div of the component your element is in, as an indication that your element is loaded. Then from that element, use the query api to get your element without any implicit wait.

@stevepryde please correct me if you have a better idea.
