### ISSUE TITLE
Unusable error message when anything but 200 OK is returned

### ISSUE THREAD

**Issue by TilBlechschmidt** [stevepryde/thirtyfour#50]
When the Selenium Endpoint does not return a valid JSON object but instead throws some kind of error (e.g. `502 Bad Gateway`) that error code and the response body is not part of the thrown error. Instead, it contains `null`:

```
The WebDriver server returned an unrecognised response: Server returned unknown response: null
```

Here is the corresponding HTTP response captured with Wireshark:

```
HTTP/1.1 502 Bad Gateway
Content-Length: 148
Date: Fri, 07 May 2021 07:42:20 GMT
Content-Type: text/plain; charset=utf-8

Unable to forward request: error trying to connect: tcp connect error: Operation timed out (os error 110)
```

It would be neat if that error message and code would be propagated instead of discarded 🙂

**Comment by TilBlechschmidt** [comment]
It looks like this problem originates in [this method](https://github.com/stevepryde/thirtyfour/blob/dd8830dfd359ee53a3a20245761413e559170c9c/src/error.rs#L173). It takes a status code and a deserialised JSON value. However, since the response body is not a JSON object, it can not be deserialised and hence `null` is returned.

The minimal change I'd propose is to change [line 178](https://github.com/stevepryde/thirtyfour/blob/dd8830dfd359ee53a3a20245761413e559170c9c/src/error.rs#L178) to also return the status code. The optimal change would be to change it so that the non-deserialised body content is passed to the function (or alternatively, just squeeze the raw body into a `serde_json::Value` of type `String` and pass that to the function in case the deserialisation fails).

**Comment by stevepryde** [comment]
So the `WebDriverError::UnknownResponse` variant could be modified to include status code and the body (as text?). Would that work for you?

**Comment by TilBlechschmidt** [comment]
Yeah that'd be the preferred solution! That way it would be possible to debug errors where something went horribly wrong and you don't get JSON back 😉

**Comment by stevepryde** [comment]
Ok I might put up a PR and get you to check it. Give me a few minutes

**Comment by stevepryde** [comment]
https://github.com/stevepryde/thirtyfour/pull/51

**Comment by TilBlechschmidt** [comment]
Works as expected (see PR)

**Comment by TilBlechschmidt** [comment]
Thank you for the very quick fix! 😊

**Comment by stevepryde** [comment]
Haha all good - I just happened to check my notifications after you sent it. Easy fix (and something I've wanted as well). Thanks for pointing out where the change needed to go. That saved a lot of time.

I'll publish this version now

**Comment by stevepryde** [comment]
v0.24.0 is live :)
