### ISSUE TITLE
WebElement::find_element lifetime is fully correct?

### ISSUE THREAD

**Issue by zhiburt** [stevepryde/thirtyfour#57]
Hey @stevepryde are these lifetime discrepancies are intentional?

WebElement

```rust
    pub async fn find_element(&self, by: By<'a>) -> WebDriverResult<WebElement<'a>>;
```

WebDriver

```rust
    async fn find_element<'a>(&'a self, by: By<'_>) -> WebDriverResult<WebElement<'a>>;
```

What I am trying to say is that why we bound to `'a` lifetime in a `WebElement`?

*Kind of bump on the issue with this :disappointed_relieved:

**Comment by stevepryde** [comment]
You were correct to question it. I remember I did get confused with those lifetimes previously. Your changes make much more sense. Thanks :)
