### ISSUE TITLE
Usage of invalid driver causes an endless execution?

### ISSUE THREAD

**Issue by zhiburt** [stevepryde/thirtyfour#62]
Hey @stevepryde,
so I encounter if you're running in your environment chromedriver but provide thirtyfour with firefox Capabilities `Webdriver::new` function never returns.

You can run this test to repeat it.

https://github.com/Plato-solutions/doonop/blob/d5ace574ac64477a9dea3e07b4db66a63d2d01ab/tests/crawling.rs#L27

**Comment by stevepryde** [comment]
Is this the case even if you specify a timeout? Does chromedriver send a response?

**Comment by zhiburt** [comment]
>  Does chromedriver send a response?

No

> Is this the case even if you specify a timeout?

How I suppose to do it?

This is how I configure the driver.

```rust
            let mut cops = DesiredCapabilities::firefox();
            cops.set_headless()?;
            // by this option we try to resolve CAPTCHAs
            cops.add("unhandledPromptBehavior", "accept")?;

            if let Some(p) = cfg.proxy.as_ref() {
                let proxy = convert_proxy(p);
                cops.set_proxy(proxy)?;
            }

            WebDriver::new(cfg.webdriver_address.as_str(), &cops).await?
```

**Comment by stevepryde** [comment]
There is a `new_with_timeout` constructor which allows you to specify a timeout.

**Comment by zhiburt** [comment]
`new_with_timeout` works :+1: 

Maybe it's worth mentioning in `Webdriver::new` about this behavior?

**Comment by stevepryde** [comment]
I'm going to change new() to default to a 120 second timeout. Users can call `new_with_timeout(..., None)` if they want no timeout.

**Comment by stevepryde** [comment]
Added note about timeout in `WebDriver::new`
