### ISSUE TITLE
Downloading a file

### ISSUE THREAD

**Issue by mkroman** [stevepryde/thirtyfour#65]
Hi,

I have a form that I want to submit, which then prompts a file download with `Content-Disposition: attachment`

Is it possible to download this file using thirtyfour/chromedriver, to a specific directory, or somehow interact with the download request?

**Comment by stevepryde** [comment]
You can set the default download directory in the chrome profile when starting the browser. You can do this via the `download.default_directory` and `download.prompt_for_download` settings.

Then you can just trigger the download and then look for any new files in that directory that you set.
