### ISSUE TITLE
Idiomatically await elements of a Vec

### ISSUE THREAD

**Issue by bcpeinhardt** [stevepryde/thirtyfour#67]
Hey there! This is really about Async/Await in general but as I'm encountering the issue in the context of Selenium I thought you might have a good answer. I'm processing hrefs from a list of links scraped from the page, and I want to await every call to get the href attribute, but I can't do async in a map.
My code:
```
// Pull the urls from the href attribute of each link and filter out urls that have already been processed
            let new_order_urls = new_order_links.iter()
            .map(|link| { link.get_attribute("href").await })
            .map(|href_result_option| {
                if let Ok(Some(url)) = href_result_option {
                    return url;
                }

                // Gets filtered out of the list, can't crash on error or no href, will need to try to get the url on the next go round
                "error_url".to_string()
            })
            .filter(|url| !enforced_orders.contains(url)).collect();
```
This of course gives the error
```
error[E0728]: `await` is only allowed inside `async` functions and blocks
  --> src\unassigned_email_queue.rs:68:27
   |
68 |             .map(|link| { link.get_attribute("href").await })
   |                  ------   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ only allowed inside `async` functions and blocks
   |                  |
   |                  this is not `async`
```
What is the best way to call and await get_attribute for each link in the list?

**Comment by bcpeinhardt** [comment]
Current ugly solution
```
let mut future_web_driver_result_option_strings = Vec::new();
            for link in new_order_links.iter() {
                future_web_driver_result_option_strings.push(link.get_attribute("href"));
            }
            let web_driver_result_option_strings =
                futures::future::join_all(future_web_driver_result_option_strings).await;

            let urls = web_driver_result_option_strings
                .into_iter()
                .map(|wdros| {
                    if let Ok(Some(url)) = wdros {
                        return url;
                    }

                    "error".to_string()
                })
                .filter(|url| !enforced_orders.contains(&url))
                .collect::<Vec<String>>();
```

**Comment by stevepryde** [comment]
Btw there isn't a lot of point in doing the selenium calls in parallel because they will be executed sequentially anyway. This is a design decision to make browser testing more predictable but I could see use cases where parallelism might be beneficial, such as this one.

For now you can simplify by doing each request in series and awaiting each time (without join_all()). Otherwise your solution seems to be on the right track. It doesn't look so ugly to me.
Do you actually want the error ones in the list? It seems to me that you probably want to filter by result and collect all the Ok vs Err ones in different vecs.

**Comment by bcpeinhardt** [comment]
That's probably what I'll end up doing with the errors. I was just quickly trying to set up a scenario where these urls are sent via a multi producer multi consumer channel to other WebDrivers for processing as part of some discovery I'm doing.

**Comment by bcpeinhardt** [comment]
Hello,
I just wanted to follow up on the discussion of how Selenium handles these calls. I totally see why the individual selenium calls from a single driver ought to be in order. If I connect to a standalone selenium server with /wd/hub and then connect two drivers to it, will calls made by each of those drivers come back asynchronously or in order? I don't really want to mess with docker and/or VMs and whatnot because I'm just running on my local machine, but I really do need the async behavior (I don't want one driver doing nothing because another driver is waiting on the server). Right now I'm spinning up geckodrivers individually on open ports and connecting directly to guarantee async behavior, but this is definitely a hassle.

**Comment by stevepryde** [comment]
The mutex is only per webdriver instance so there is no reason why separate webdriver instances could not execute requests in parallel.

Have a read of the Tokio `join!` call for more details.

**Comment by stevepryde** [comment]
https://rust-lang.github.io/async-book/06_multiple_futures/01_chapter.html
