### ISSUE TITLE
Firefox is set but using chrome

### ISSUE THREAD

**Issue by makorne** [stevepryde/thirtyfour#71]
Please read this:  #[Firefox is set but using chrome](https://github.com/TilBlechschmidt/ParallelSeleniumTest/issues/1)

**Comment by stevepryde** [comment]
@makorne so if I understand correctly what you want is just the Chrome equivalent of `set_accept_untrusted_certs()` ?

**Comment by stevepryde** [comment]
Added `ChromeCapabilities::set_ignore_certificate_errors()` in `v0.27.1`.
Let me know if this is not what you were after.
