### ISSUE TITLE
Is it possible to load two pages in parallel?

### ISSUE THREAD

**Issue by ArbilGit** [stevepryde/thirtyfour#74]
Hi! First of all, let me say that - having worked with selenium across multiple languages - your crate is the most fun!

Is it possible to load two pages in parallel, in two tabs in a single webdriver, and await both navigations? I've never succeeded in doing that in other selenium implementations.

This code seems to load the pages sequentially:

    let caps = DesiredCapabilities::chrome();
    let driver = Arc::new(WebDriver::new("http://localhost:4444", &caps).await?);
    let driver2 = driver.clone();
    tokio::spawn(async move {
        //longish loading website to see if parallel
        driver2.get("https://www.ebay.com").await;
    });

    driver
        .in_new_tab(|| async { driver.get("https://www.google.com").await })
        .await?;

Thanks!

**Comment by ArbilGit** [comment]
Thank you very much the detailed reply. I suspected the one-page-at-a-time design of selenium cannot be circumvented. Do you know if CDP can provide "navigation finished" callbacks/events for two tabs in parallel? That would allow implementing the parallel async navigation

**Comment by ShayBox** [comment]
Maybe some way to goto without waiting for the page to load, or qol methods on windowhandle to goto, which in the background quickly switches, goto, then switches back, without waiting for the page to load
