### ISSUE TITLE
[Help Wanted] how to set Cookie

### ISSUE THREAD

**Issue by lexasub** [stevepryde/thirtyfour#79]
i want something:
 let cookie  = {"id":{"s":"a",...},..};
//..
driver.add_cookie(Cookie::new(cookie));
what i do wrong?

**Comment by stevepryde** [comment]
See the documentation: https://docs.rs/thirtyfour/latest/thirtyfour/prelude/trait.WebDriverCommands.html#method.add_cookie

**Comment by lexasub** [comment]
also i want set 

driver.set_preference("csrftoken", csrftoken);

> See the documentation: https://docs.rs/thirtyfour/latest/thirtyfour/prelude/trait.WebDriverCommands.html#method.add_cookie

i want add many cookies(copy from browser & paste)

**Comment by stevepryde** [comment]
I'm not sure what you're asking for. The example in the documentation I linked to shows how to set a cookie in the browser.
Also there is no csrftoken in selenium itself and no `set_preference()` method on `WebDriver`.

Please read through the examples on github and also the examples in the documentation on https://docs.rs/thirtyfour
