### ISSUE TITLE
help opening new tab

### ISSUE THREAD

**Issue by mzagrabe** [stevepryde/thirtyfour#81]
Greetings,

Thank you for writing thirtyfour.

I am attempting to follow a code snippet example from src/webdrivercommands.rs.

I'd like to open a new tab and browse to google.com.

My firefox browser currently has 3 pinned tabs. What happens when I run the following code is that the second pinned tab is selected and that tab browses to google.com.

```
use thirtyfour::prelude::*;
use tokio;

#[tokio::main]
async fn main() -> WebDriverResult<()> {
    let caps = DesiredCapabilities::firefox();
    let driver = WebDriver::new("http://localhost:4444", &caps).await?;

    driver.execute_script(r#"window.open("about:blank", target="_blank");"#).await?;
    // Get window handles and switch to the new tab.
    let handles = driver.window_handles().await?;
    driver.switch_to().window(&handles[1]).await?;
    // We are now controlling the new tab.
    driver.get("https://google.com").await?;

    driver.quit().await?;

    Ok(())
}

```

Any ideas of what I should be doing?

Thanks for the help!

-m

**Comment by bcpeinhardt** [comment]
Hello!

It comes down to the line
```
driver.switch_to().window(&handles[1]).await?;
```
handles[1] is the second tab in the array of tabs (since we start at 0), so to switch to the fourth tab, it would be 
```
driver.switch_to().window(&handles[3]).await?;
```
Alternatively, check out the method in_new_tab in the webdriver commands to do this more conveniently.
