### ISSUE TITLE
Breaking Changes:: Thirtyfour will rebase on top of fantoccini in an upcoming version

### ISSUE THREAD

**Issue by stevepryde** [stevepryde/thirtyfour#84]
See also: https://github.com/jonhoo/fantoccini/issues/145

After some discussion started in the above thread, I've decided to refactor `thirtyfour` to use `fantoccini` "under-the-hood" and provide more advanced features on top.

Fantoccini aims to be a complete but minimal client for the `W3C WebDriver` specification, without adding any unnecessary features on top. It's likely `CDP` (Chrome Devtools Protocol) will also fall under that umbrella now that it is officially part of Selenium 4.x.

Rather than continue to provide duplicate functionality in `thirtyfour`, it makes more sense to defer to `fantoccini` for all of the underlying `WebDriver` commands, and types, etc.

Meanwhile `thirtyfour` will continue to focus on providing a batteries-included, polished interface to take care of automating browsers.

The changes required are as follows:
* Implement all remaining `WebDriver` commands in `fantoccini` (this work has started already)
* Refactor `thirtyfour` to use `fantoccini` to provide all basic `WebDriver` functionality. Method names will likely remain similar to what currently exists in `thirtyfour`, which should keep things fairly backwards-compatible.
* Support for non-tokio runtimes will be discontinued, due to `fantoccini` only providing a single HTTP client. Hopefully this shouldn't impact many users (if any)
* The `WebDriver` and `WebElement` types will remain, however several other types such as `Cookie` and `WindowHandle` will be changed to use the `fantoccini`-exported types.
* Backwards-compatibility, at least in terms of supported features, will be a high priority. There will be some minor interface changes but hopefully the impact will be small. These changes will be listed once this is released.

**Comment by stevepryde** [comment]
This is now in `main` and will be released as `v0.29.0` once `fantoccini v0.19.0` is released

**Comment by crasite** [comment]
`fantoccini` uses `Cookie` from `cookie-rs`  which doesn't support serialization. Should we keep our 0.28's `Cookie` implementation to enable serialization and de serialization?

**Comment by stevepryde** [comment]
I'd prefer to either change the upstream implementation or otherwise add a serde wrapper as per this serde feature: https://serde.rs/remote-derive.html

**Comment by stevepryde** [comment]
Thirtyfour v0.29.0 has now been released, based on fantoccini v0.19.0
