### ISSUE TITLE
executing javascript before open the URL

### ISSUE THREAD

**Issue by knassar702** [stevepryde/thirtyfour#88]
Hey @stevepryde, I appreciate your work but there's a missing feature I really need in my project that is `Executing javascript before open the URL` , your crate has a Js executing function, that's what I saw on https://docs.rs/thirtyfour/0.28.1/thirtyfour/struct.WebDriver.html
 but it will be executed after opening the URL for doing some DOM parsing or something

is it possible in the current version?

best regards
@knassar702

**Comment by stevepryde** [comment]
Have you tried it?

This crate follows the WebDriver spec. If the feature you are requesting does not already work then there isn't really any way to add it.

If you are able to reproduce it with another selenium library (e.g. java or python) then let me know and I can make this crate work the same

**Comment by h4cnull** [comment]
your can use this code to do it, exec js script before page loading.

`let dev_tools =  ChromeDevTools::new(&driver.handle);`
`let x = dev_tools.execute_cdp_with_params("Page.addScriptToEvaluateOnNewDocument", serde_json::json!({"source":"console.log(\"before loaded\")"})).await?;`
